version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./api:/app
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./client:/app

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
