version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    networks:
      - app-network


  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
